language: ruby
rvm:
- 2.4.1
services:
- postgresql
script:
- bundle exec rails db:migrate
- bundle exec rake db:test:prepare
- bundle exec rspec
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
before_install:
  - ./ecr_credentials.sh
addons:
  code_climate:
    repo_token: 
    secure: KNmknq20T/48h4RHQQtUYii97pLLwFQoLT6kWkh/aTRyac9UAPo6xhYHzKZpf+TSg+/GwG/s8BbWC9hxpEY5zIDi31SsHwsNfS6GOkqSgMPsjWAnNfAYiaYO577EQLsE1FrhJOLMYlbKQO8QPqxDb8Wd+0eUobpT+SJQLODohvFbwxOSFeXm/83IkZJqEganQAV6hjRIHtEPn7UtnlfoZJLuP5WgjhxaZHbgG9k7Qh1LirBhj0Yjaku7Qcm3DHrhm6JpSz5vp5XgICLMZVvl8lzrI3INebq5nVgVrd6PD/kdeyttNgwsQP9eu/h75ZfEboUBq9bPKlqASqW3KUyD5OWiSILqix6gukl1KMu0nsmDHbNIDfd00NXqLY+zYItMNtRqdPSIrxbNW/ajGA6V5N0Kdh4g4psB4bwI0qURSMBlpwMBtamINmQTFavlEnOHpJxRVsKDHTKg93cflGGNHyA6nSEDli2BgveH9Y1GBaxLgKb1619FnRGOlY3UDVfpW1M5k4BE4tr1LaOu81cS/3IDEvHzQXeu0hdK9SZo5hRq9e9h38P3LPF8p1GTFCB5WpeUfFknGg1vNu/9iDLuBs1X+oSGOmkf8V8s62n3+kLs8e95+Y+tmFhno/ZH585Rny5AwrU/8xDgGKLItrFm4uKlGypzpv42YqB2MViMdw4=
env:
  global:
  - secure: TR1FsAyDbxmcll4uifvXcxb8n1FJa66Mc6Z2ZMjHSXapH19r+F8/DVyA/Tldc/JUszM/Le4n0zbj7IajPh7JVBK83H1WYg6vvT15BZR3PAS2q4Qf3Sb+VSogEx/xqVbIU7gSIw6yjYMsTTApHlBfmq5ZFMxgFnwgDOmlYhlV0Z24LHBGKYlPXXzpvY+/qP80/Izct3IG4+LFtVsnFBu9jDlvpDyHU4TzPzBG/cnqOJ4gCXyZvXcJ8EKi2wL80vkZQvKRW6Y8m7UMKhe/a1kQVEK/3zGozkIjtJHWTfCFubFRdAfBB1llL/tlwB6PHDLlc2XfuQPfQTLB9VkxCmCD9v7gfU0+sWTv1mxT1v7P7zYMKTndQspTR7EwVf5Lh8TveaBimAuZvFMOStCyngfPoaQ6VzVT9ZJJ1ML2PZjBH3+6k1YqDCkY71SrFBZlhTNM8AsP4Mt2L3h6fxBvcvdsokIPjEi7RftJnhVTx5PbO2MNpu1cVwTVb84QBEvTIEPQsu9LsY/D06m1NtYZnM9j67kffO/ltV0K0+IELFPW1PWL0NB8l+mwQWq4ns/QrORd7xTvFBizoGHQR5C5tSXlCxgwSyGNmarIVSB2Vgb0DYO5Vn0qnIa4/1MqldBWQrgFz4oeH73QrTM0DuavbY+q+3UMkiZO+i5iahoJunxfAbw=
  - secure: U+j7xxMhLZ2U2j3mRqxd+hCcy9kZIpxPGt8K0WGpOoBUUEW80LVpTLMIOdYV/XdhLrFx+gegpKlqJbPZQxMTre1Y50xw4uT5SWgCQj/mCdTfMTFCnP0LFr+ezNmK7Vgu6Uchez2xebLcrra7R4L8z5pmBRx2L1SeSBFbsdH3W6DfhsU6jktQraAG78CVOpvZm20dt0MbazoJBMrucRPlQKyE3w/eLCIC/4gJbeNlkdrV5EHxPlaSKFwky8faua1oKaGHHDUar4D8BIGEiJCYw0uorrZq1w94XzItY49ZyDWhfepNRSa/haW+ssiT2XV3aqbBZcyyY4eohzRtfbM4D7p/Wls8vbRqFv2QD+tr0l881RXrIniJPrE9cs0UpLzHT7GU6//ll6pCrpqr9sEw3nYO0TTrnpC8bHCazLseaa6rcON1ZjKm76+x19bs5c8C+qFG7dRsl6FP/oB2goNYhx2Xn8c11nmToFw0S/a/gFTRUVNfyHn9kjB3eSwj92CV/kTcIr2nzELRrSXVO+UNwWSF1vZuswyJgR8dLhhtHSEfgAzbdb/zJ+qybUGnp2BEuZffsf6kcGiDb7duBeD5N+21BGe2vKlGXyE6cKDO56gnIamCK7ausKEM7jX2BZsIe8458aaRMXmwARefX4lYAja+Wph/Ufikxp9yh75TKs8=
